<?php

namespace App\Http\Controllers\Moto;

use App\Http\Controllers\Controller;
use App\Http\Repositories\Moto\CertificatesRepo as Repo;
use App\Http\Repositories\Moto\ItemsRepo;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;


class CertificatesController extends Controller
{
    public function  __construct(Request $request, Repo $repo, Route $route, ItemsRepo $itemsRepo)
    {

        $this->request  = $request;
        $this->repo     = $repo;
        $this->route    = $route;

        $this->section          = 'certificates';
        $this->data['section']  = $this->section;

        $this->data['items_id'] = $route->getParameter('id');
        $this->itemsRepo = $itemsRepo;

        $id = $this->route->getParameter('id');
        $this->data['models'] = $itemsRepo->find($id)->Certificates;

    }
    

    public function store()
    {
        parent::store(); // TODO: Change the autogenerated stub
        return redirect()->route('moto.items.index');
    }
}
