<?php

namespace App\Http\Controllers\Moto;

use App\Http\Controllers\Controller;
use App\Http\Repositories\Moto\CertificatesRepo as Repo;
use App\Http\Repositories\Moto\ItemsRepo;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;


class CertificatesController extends Controller
{
    protected  $itemsRepo;

    public function  __construct(Request $request, Repo $repo, Route $route, ItemsRepo $itemsRepo)
    {

        $this->request  = $request;
        $this->repo     = $repo;
        $this->route    = $route;

        $this->section          = 'certificates';
        $this->data['section']  = $this->section;

        $this->itemsRepo = $itemsRepo;
        $this->data['items_id']  = $this->route->getParameter('id');


    }

    public function create()
    {
        $items_id = $this->data['items_id'];
        $this->data['models'] = $this->itemsRepo->find($items_id)->Certificates;

        return parent::create(); // TODO: Change the autogenerated stub
    }

   public function edit()
   {
       $items_id = $this->data['items_id'];
       $this->data['models'] = $this->itemsRepo->find($items_id)->Certificates;

       $this->data['activeBread'] = 'Editar';
       return view(config('models.'.$this->section.'.editView'))->with($this->data);

   }

}
