<?php

namespace App\Http\Controllers\Moto;

use App\Entities\Moto\Sales;
use App\Http\Controllers\Controller;
use App\Http\Repositories\Configs\VouchersRepo;
use App\Http\Repositories\Moto\BrandsRepo;
use App\Http\Repositories\Moto\CategoriesRepo;
use App\Http\Repositories\Moto\FilesRepo as Repo;
use App\Http\Repositories\Moto\Form12Repo;
use App\Http\Repositories\Moto\Form59Repo;
use App\Http\Repositories\Moto\ProvidersRepo;
use App\Http\Repositories\Moto\SalesRepo;
use Barryvdh\DomPDF\PDF;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;


class FilesController extends Controller
{
    public function  __construct(Request $request, Repo $repo, Route $route,VouchersRepo $vouchersRepo, SalesRepo $salesRepo, Form12Repo $form12Repo, Form59Repo $form59Repo)
    {

        $this->request  = $request;
        $this->repo     = $repo;
        $this->route    = $route;
        $this->form12Repo    = $form12Repo;
        $this->form59Repo    = $form59Repo;

        $this->section          = 'files';
        $this->data['section']  = $this->section;

        $this->data['invoices'] = $vouchersRepo->listsDataWhere('numero','id',['tipo' => 'F']);

        $this->data['sales'] = $salesRepo->listsData('id','id');

        $this->data['estado'] = config('models.files.estado');

        $this->data['ubicacion'] = config('models.files.ubicacion');

        $this->data['municipios'] = [1 => "Moreno",2 => "Morón", 3 => "CABA"];

        $this->data['sa'] = Sales::with('Items')->with('Clients')->with('BranchesConfirm')->with('Vouchers')->with('Payments')->find(1);
    }

    public function edit()
    {
        return parent::edit(); // TODO: Change the autogenerated stub
    }


    public function showForm12(PDF $pdf){
        $models = $this->form12Repo->find($this->route->getParameter('form'));

        $sales = $models->files->sales;

        $pdf->setPaper('a4', 'portland')->loadView('moto.files.formulario.form12',compact('sales','models'));

        return $pdf->stream();
    }

    public function form12(PDF $pdf, Sales $sales){

        $sales = $sales->with('salesItems','clients')->find($this->request->get('sales_id'));

        $this->request['files_id'] = $this->route->getParameter('id');


        $models = $this->form12Repo->create($this->request);

        $pdf->setPaper('a4', 'portland')->loadView('moto.files.formulario.form12',compact('sales','models'));
//        $pdf->setPaper('a4', 'portland')->loadView('moto.files.formulario.form12',[$sales,$models]);

        return $pdf->download();

    }


    public function form59(PDF $pdf){

        $pdf->setPaper('a4', 'portland')->loadView('moto.files.formulario.form59');

        return $pdf->stream();
    }

}
