<?php

namespace App\Http\Controllers\Moto;

use App\Http\Controllers\Controller;
use App\Http\Repositories\Moto\ModelsListsPricesItemsRepo;
use App\Http\Repositories\Moto\ModelsListsPricesRepo as Repo;
use App\Http\Repositories\Moto\ModelsRepo;
use App\Http\Repositories\Moto\ProvidersRepo;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Session;


class ModelsListsPricesController extends Controller
{
    protected $modelsRepo;
    protected $modelsListsPricesRepo;

    public function  __construct(Request $request, Repo $repo, Route $route, ProvidersRepo $providersRepo, ModelsRepo $modelsRepo, ModelsListsPricesItemsRepo $modelsListsPricesItemsRepo)
    {

        $this->request  = $request;
        $this->repo     = $repo;
        $this->route    = $route;

        $this->section          = 'modelsListsPrices';
        $this->data['section']  = $this->section;

        //data
        $this->data['providers'] = $providersRepo->ListsData('name','id');
        $this->data['models_lists'] = $modelsRepo->ListsData('name','id');

        $this->modelsRepo =  $modelsRepo;
        $this->modelsListsPricesRepo =  $modelsListsPricesItemsRepo;
    }

    public function edit()
    {
        $this->data['modelItems'] = $this->modelsListsPricesRepo->find($this->route->getParameter('id'));

        return parent::edit(); // TODO: Change the autogenerated stub
    }

    public function addItems(ModelsListsPricesItemsRepo $modelsListsPricesItemsRepo)
    {
        $modelsListsPricesItemsRepo->create($this->request);

        return redirect()->route('moto.modelsListsPrices.edit',$this->request->models_lists_prices_id);
    }

    public function editItems(ModelsListsPricesItemsRepo $modelsListsPricesItemsRepo)
    {
        $this->data['modelItems'] = $modelsListsPricesItemsRepo->find($this->route->getParameter('id'));

        return redirect()->route('moto.modelsListsPrices.editItem',$this->route->getParameter('id'))->with($this->data);
    }

    public function deleteItems(ModelsListsPricesItemsRepo $modelsListsPricesItemsRepo)
    {
        $modelsListsPricesItemsRepo->destroy($this->route->getParameter('id'));

        return redirect()->route('moto.modelsListsPrices.edit',$this->route->getParameter('model'));
    }

    /*
    public function addItems()
    {
        $data   = $this->request;
        if(empty($data))
            return ["error" => "Debes completar los campos"];
        else{

            $model  = $this->modelsRepo->find($data->models_id);

            $arr =  session()->has($this->section.'Items') ? session($this->section.'Items') : [];

            $newItem =
            [
                'models_id' => $data->models_id,
                'price_list' => $data->price_list,
                'price_net' => $data->price_net,
                'max_discount' => $data->max_discount,
                'obs'=> $data->obs
            ];

            array_push($arr, $newItem);

            session()->put($this->section.'Items',$arr);

            return [
                    'error' => 'Se agregó correctamente el item',
                    'success' => [
                        'models_name' => $model->name,
                        'models_id' => $model->id,
                        'price_list' => $data->price_list,
                        'price_net' => $data->price_net,
                        'max_discount' => $data->max_discount
                    ]
            ];
        }
    }

    public function editItems()
    {
        $data   = $this->request;
        if(empty($data))
            return ["error" => "Debes completar los campos"];

        else{

            $model  = $this->modelsRepo->find($data->models_id);

            $arr =  session()->has($this->section.'Items') ? session($this->section.'Items') : [];

            $newItem =
            [
                'models_id' => $data->models_id,
                'price_list' => $data->price_list,
                'price_net' => $data->price_net,
                'max_discount' => $data->max_discount,
                'obs'=> $data->obs
            ];

//            array_push($arr, $newItem);

            foreach($arr as $ind => $val){
                if($val["models_id"] == $data->id){
                    $arr[$ind] = $newItem;
                }
            }

            session()->put($this->section.'Items',$arr);

            return [
                    'error' => 'Se editó correctamente el item',
                    'success' => [
                        'models_name' => $model->name,
                        'models_id' => $model->id,
                        'price_list' => $data->price_list,
                        'price_net' => $data->price_net,
                        'max_discount' => $data->max_discount
                    ]
            ];
        }
    }

    public function deleteItems()
    {
        $data   = $this->request;
        $arr =  session()->has($this->section.'Items') ? session($this->section.'Items') : [];

        foreach($arr as $ind => $val){
            if($val["models_id"] == $data->id){
                unset($arr[$ind]);
            }
        }

        session()->put($this->section.'Items',$arr);

        return "Se eliminó correctamente el item";
    }
    */
}
