<?php

namespace App\Http\Controllers\Configs;

use App\Http\Controllers\Controller;
use App\Http\Helpers\ApiFEHelper;
use App\Http\Repositories\Configs\VouchersRepo as Repo;

use App\Http\Repositories\Moto\SalesRepo;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;


class VouchersController extends Controller
{
    protected $apiFe;

    public function __construct(Request $request, Repo $repo, Route $route)
    {

        $this->request = $request;
        $this->repo = $repo;
        $this->route = $route;

        $this->section = 'vouchers';
        $this->data['section'] = $this->section;

        $this->data['tipos'] = config('models.vouchers.tipos');
        $this->data['letras'] = config('models.vouchers.letras');


    }


    public function store()
    {
        $api = new ApiFEHelper();

        $data = [
            'punto_venta' => 9998,
            'tipo' =>'F',
            'letra' => 'B',
            'concepto' => 'P',
            'tipo_documento' => "DNI",
            'numero_documento' => 27535920,
            'fecha' => "20170325",
            'importe_total' => 1210.00,
            "importe_total_no_gravado" => 0.0,
            "importe_total_neto_gravado" => 1000.0,
            "importe_total_operaciones_exentas" => 0.0,
            "importe_total_otros_tributos" => 0.0,
            "importe_total_iva" => 210.0,
            "iva" => [["base_imponible" => 1000,"alicuota" => 21.00 ,   "importe"=> 0.02] ],

        ];

        $api->call('POST', $data);

        dd($api->getResultado());
        $comprobante = parent::store(); // TODO: Change the autogenerated stub
    }

    public function fromSales(SalesRepo $salesRepo)
    {
        $this->data['activeBread'] = 'Nuevo Comprobante';
        $this->data['sale'] = $salesRepo->find($this->route->getParameter('salesId'));

        return view('configs.vouchers.formFromSales')->with($this->data);
    }

}
