<?php

namespace App\Http\Controllers\Configs;

use App\Http\Controllers\Controller;
use App\Http\Helpers\ApiFEHelper;
use App\Http\Repositories\Configs\VouchersRepo as Repo;

use App\Http\Repositories\Moto\SalesRepo;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;


class VouchersController extends Controller
{
    protected $apiFe;

    public function __construct(Request $request, Repo $repo, Route $route)
    {

        $this->request = $request;
        $this->repo = $repo;
        $this->route = $route;

        $this->section = 'vouchers';
        $this->data['section'] = $this->section;

        $this->data['tipos'] = config('models.vouchers.tipos');
        $this->data['letras'] = config('models.vouchers.letras');
        $this->data['tipoDocumento'] = config('models.vouchers.tiposDocumento');


    }


    public function store()
    {
        $api = new ApiFEHelper();

        $data =
            [
                'punto_venta' => $this->request->punto_venta,
                'tipo' => $this->request->tipo,
                'letra' => $this->request->letra,
                'concepto' => 'P',
                'tipo_documento' => $this->request->tipo_documento,
                'numero_documento' => $this->request->dni,
                'fecha' => date('Ymd', strtotime($this->request->fecha)),
                'importe_total' => $this->request->importe_total,
                "importe_total_no_gravado" => 0.0,
                "importe_total_neto_gravado" => $this->request->importe_total / 1.21,
                "importe_total_operaciones_exentas" => 0.0,
                "importe_total_otros_tributos" => 0.0,
                "importe_total_iva" => ($this->request->importe_total) - ($this->request->importe_total / 1.21),
                "iva" => [["base_imponible" => $this->request->importe_total / 1.21, "alicuota" => 21.00, "importe" => ($this->request->importe_total) - ($this->request->importe_total / 1.21)]],

            ];

        $api->call('POST', $data);

        $resultado = $api->getResultado();


        if ($resultado->status->estado != 'OK')
            return redirect()->back()->withErrors([$resultado->status]);
        else
        {
            $this->request['numero'] = $resultado->comprobante->numero ;
            $this->request['cae'] = $resultado->comprobante->cae ;
            $this->request['vencimiento_cae'] = $resultado->comprobante->vencimiento_cae ;

            return parent::store(); // TODO: Change the autogenerated stub
        }


    }

    public function fromSales(SalesRepo $salesRepo)
    {
        $this->data['activeBread'] = 'Nuevo Comprobante';
        $this->data['sale'] = $salesRepo->find($this->route->getParameter('salesId'));

        return view('configs.vouchers.formFromSales')->with($this->data);
    }

}
