<?php
namespace App\Http\Repositories\Moto;

use App\Entities\Moto\Checkbooks;
use App\Http\Repositories\BaseRepo;


class CheckbooksRepo extends BaseRepo {
    
    public function getModel()
    {
        return new Checkbooks;
    }


    public function create($data)
    {
        for($i = $data->from ; $i <= $data->to ; $i++)
        {
            $data['n_cheque'] = $i;
            $model = parent::create($data);
        }


        return $model; // TODO: Change the autogenerated stub
    }

}