<?php
namespace App\Http\Repositories\Moto;

use App\Entities\Moto\Files;
use App\Http\Helpers\ImagesHelper;
use App\Http\Repositories\BaseRepo;


class FilesRepo extends BaseRepo {
    
    public function getModel()
    {
        return new Files;
    }

    public function create($data)
    {
        $model =  parent::create($data); // TODO: Change the autogenerated stub

        $this->createImageFiles($model, "dni_photocopy_file",$data);
        $this->createImageFiles($model, "proof_of_cuil_file",$data);
        $this->createImageFiles($model, "form_01_file",$data);

        return $model;
    }

    public function update($id, $data)
    {
        $model =  parent::update($id, $data->except(["dni_photocopy_file","proof_of_cuil_file","form_01_file"]));

        $this->createImageFiles($model, "dni_photocopy_file",$data);

        $this->createImageFiles($model, "proof_of_cuil_file",$data);
        $this->createImageFiles($model, "form_01_file",$data);

        return $model;

    }


    public function createImageFiles($model,$attribute, $data){
        
        if(isset($data->$attribute) && !is_null($data->$attribute) )
        {
            $time = time();
            $name = $time.$data->$attribute->getClientOriginalName();

            if(!empty($model->$attribute) && is_file($model->$attribute))
                unlink($model->$attribute);

            $data->file($attribute)->move(config('models.'.$model->section.'.'.$attribute.'_path'),$name);

            $model->$attribute = config('models.'.$model->section.'.'.$attribute.'_path').$name;
            $model->save();
        }
    }

}