<?php
namespace App\Http\Repositories\Moto;

use App\Entities\Moto\Forms;
use App\Http\Repositories\BaseRepo;


class FormsRepo extends BaseRepo {
    
    public function getModel()
    {
        return new Forms();
    }


    public function create($data)
    {
        $from =  $data->from;
        $to = $data->to;


        for($i=$from;$i <= $to ; $i++)
        {
            $data['number'] = $i;
            $data['status'] = 1;

            $model =  parent::create($data); // TODO: Change the autogenerated stub
        }

        return $model;

    }

}