<?php
namespace App\Http\Repositories\Moto;

use App\Entities\Moto\Models;
use App\Http\Repositories\BaseRepo;


class ModelsRepo extends BaseRepo {
    
    public function getModel()
    {
        return new Models();
    }


    public function create($data)
    {
        $model =  parent::create($data); // TODO: Change the autogenerated stub
        $model->Categories()->attach($data->categories_id);
        return $model;
    }

    public function update($id, $data)
    {
        $model =  parent::update($id, $data); // TODO: Change the autogenerated stub
        $model->Categories()->sync($data->categories_id);
        return $model;

    }

    public function destroy($id)
    {
        $model =  parent::destroy($id); // TODO: Change the autogenerated stub
        $model->Categories()->detach();
        return $model;

    }

}