<?php
namespace App\Http\Repositories\Moto;


use App\Entities\Moto\ModelsListsPrices;
use App\Http\Repositories\BaseRepo;


class ModelsListsPricesRepo extends BaseRepo {
    
    public function getModel()
    {
        return new ModelsListsPrices();
    }

    public function create($data)
    {
        $model = parent::create($data); // TODO: Change the autogenerated stub

        if(session()->has('items')){
            foreach (session('items') as $item) {
                $model->ModelsListsPricesItems()->attach(['price_list'=> $item['price_list'],'price_net' => $item['price_net'],'max_discount' => $item['max_discount'],'obs' => $item['obs'],'models_id' => $item['models_id']]);
            }

        }

        return $model;
    }

    public function update($id, $data)
    {
        $model = parent::update($id, $data); // TODO: Change the autogenerated stub

        if(session()->has('items')){
            foreach (session('items') as $item) {
                $model->ModelsListsPricesItems()->sync($model->id,['price_list'=> $item['price_list'],'price_net' => $item['price_net'],'max_discount' => $item['max_discount'],'obs' => $item['obs'],'models_id' => $item['models_id']]);
            }

        }
    }

}