<?php
namespace App\Http\Repositories\Moto;

use App\Entities\Moto\Models;
use App\Entities\Moto\PurchasesOrders;
use App\Http\Repositories\BaseRepo;


class PurchasesOrdersRepo extends BaseRepo {

    public function getModel()
    {
        return new PurchasesOrders();
    }

    public function create($data)
    {
        $data['status'] = 1;


        return parent::create($data); // TODO: Change the autogenerated stub
    }

    public function ListsData($data, $id)
    {
        // para agregar un campo adelatnte return $this->model->lists($data, $id)->prepend('Seleccionar...','');
        return $this->model->where('status','3')->lists($data, $id);
    }
}


