<?php
namespace App\Http\Repositories\Moto;

use App\Entities\Moto\Sales;
use App\Entities\Moto\SalesItems;
use App\Http\Repositories\BaseRepo;


class SalesRepo extends BaseRepo
{

    public function getModel()
    {
        return new Sales();
    }

    public function create($data)
    {
        $sales = parent::create($data); // TODO: Change the autogenerated stub

        if (!is_null($data->budgets_id))
        {
            $budgetsItemsRepo = new BudgetsItemsRepo();
            $salesItemsRepo = new SalesItemsRepo();
            $itemsRepo = new ItemsRepo();

            $budgetsItems = $budgetsItemsRepo->getModel()->where('budgets_id', $data->budgets_id)->get();


            foreach ($budgetsItems as $budgetItem)
            {
                $budget = $budgetItem->budgets;
                $item = $itemsRepo->asignItem($budgetItem->models_id, $data->branches_confirm_id,$sales->id, $budgetItem->colors_id);


                if($item != false)
                {
                    $new = new SalesItems();
                    $new->sales_id = $sales->id;
                    $new->items_id = $item;
                    $new->price_actual = $budgetItem->price_actual;
                    $new->save();

                    if($budget->additionables->count() != 0)
                    {

                        foreach ($budget->additionables as $additionals)
                        {
                            $sales->additionables()->create(['additionals_id' => $additionals->id , 'amount' => $additionals->amount]);
                        }
                    };


                }else{

                    return redirect()->back()->withErrors('El Articulo no se pudo Asignar!');

                }
            }

        }

        return $sales;
    }


}