<?php
namespace App\Http\Repositories\Moto;

use App\Entities\Moto\Sales;
use App\Http\Repositories\BaseRepo;


class SalesRepo extends BaseRepo
{

    public function getModel()
    {
        return new Sales();
    }

    public function create($data)
    {
        $sales = parent::create($data); // TODO: Change the autogenerated stub

        if (!is_null($data->budgets_id))
        {
            $budgetsItemsRepo = new BudgetsItemsRepo();
            $salesItemsRepo = new SalesItemsRepo();
            $itemsRepo = new ItemsRepo();

            $budgetsItems = $budgetsItemsRepo->getModel()->where('budgets_id', $data->budgets_id)->get();

            foreach ($budgetsItems as $budgetItem)
            {
                $item = $itemsRepo->asignItem($budgetItem->models_id, $data->branches_confirm_id,$sales->id, $budgetItem->colors_id);

                dd($item);
                if($item != false)
                {
                    $salesItemsRepo->create([
                        'sales_id' => $sales->id,
                        'item_id' => $item,
                        'price_actual' => $budgetItem->price_actual,
                    ]);
                }
            }

        }

        return $sales;
    }


}