<?php
namespace App\Http\Repositories\Moto;

use App\Entities\Moto\TechnicalServices;
use App\Http\Repositories\BaseRepo;


class TechnicalServicesRepo extends BaseRepo
{

    public function getModel()
    {
        return new TechnicalServices;
    }

    public function create($data)
    {
        $model = parent::create($data); // TODO: Change the autogenerated stub

            if(isset($data->servicios))
            {
              $model->Services()->attach($data->servicios);
            }

            if(isset($data->repuestos))
            {
                $model->Repuestos()->attach($data->repuestos);
            }

        return $model;
    }

     public function update($id, $data)
     {
         $model =  parent::update($id, $data); // TODO: Change the autogenerated stub

         if(isset($data->servicios))
         {
             $model->Services()->sync($data->servicios);
         }

         if(isset($data->repuestos))
         {
             $model->Repuestos()->sync($data->repuestos);
         }

         return $model;
     }
}